// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYakfh17EqFz2zexysxtfX_sgvN0bjRZE',
    appId: '1:552121280874:web:f697e1d860e913150ddd13',
    messagingSenderId: '552121280874',
    projectId: 'website-a5924',
    authDomain: 'website-a5924.firebaseapp.com',
    storageBucket: 'website-a5924.appspot.com',
    measurementId: 'G-4Q510HSM95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1J4-5UNWOKP6IuZaIi0afspuBtSN8WRg',
    appId: '1:552121280874:android:1d1b81c78f40f4460ddd13',
    messagingSenderId: '552121280874',
    projectId: 'website-a5924',
    storageBucket: 'website-a5924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXCVq-8vmu9SzJFlZ6ssqa56v-YyPlq2g',
    appId: '1:552121280874:ios:8006c0a707ca14a60ddd13',
    messagingSenderId: '552121280874',
    projectId: 'website-a5924',
    storageBucket: 'website-a5924.appspot.com',
    iosBundleId: 'com.example.mantarayWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYakfh17EqFz2zexysxtfX_sgvN0bjRZE',
    appId: '1:552121280874:web:3f00d375479e5fdc0ddd13',
    messagingSenderId: '552121280874',
    projectId: 'website-a5924',
    authDomain: 'website-a5924.firebaseapp.com',
    storageBucket: 'website-a5924.appspot.com',
    measurementId: 'G-2LEB6F2W3B',
  );
}
